package:
  name: mist
  version: 0.92.3.0


source:
 git_url: https://github.com/Jacob-Barhak/MIST.git

build:

  number: 0

  
requirements:
  build:
    - python


  run:
    - python = 2.7
    - inspyred = 1.0
    - wxpython = 3.0


test:
  # Python imports

  # commands:

  # requires:



about:
  home: https://github.com/Jacob-Barhak/MIST
  license: GPLv3+
  summary: MIcro Simulation Tool & Monte Carlo Simulation Compiler
  dev_url: https://github.com/Jacob-Barhak/MIST


