package:
  name: mist
  version: 0.92.2.0


source:
 git_url: https://github.com/Jacob-Barhak/MIST.git

build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - astroid = astroid:main
    #
    # Would create an entry point called astroid that calls astroid.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

  
requirements:
  build:
    - python


  run:
    - python
    - inspyred
    - wxpython


test:
  # Python imports


  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.




  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.


  # requires:
    # Put any additional test requirements here.  For example
    # - nose


about:
  home: https://github.com/Jacob-Barhak/MIST
  license: GPLv3+
  summary: MIcro Simulation Tool & Monte Carlo Simulation Compiler



# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
